### ISSUE TITLE
Re-add item render hook

### ISSUE THREAD

**Issue by exaskye** [elytra/Albedo#10]
As of the ASM transformer rewrite, the item rendering hook was removed. An improved hook should be added back in.

**Comment by falkreon** [comment]
Item render hook was added in 2.0.3 - works for both equipped gear and dropped items.

**Comment by exaskye** [comment]
...doesn't look like it? This wasn't referring to lighting on items, it was referring to a hook to override item rendering. Albedo had it and I dropped it since I didn't understand the ASM and was just interested in getting lights working; we don't need to re-add it, but it's not a feature we have.
