### ISSUE TITLE
Rendering inconsistency

### ISSUE THREAD

**Issue by jena-s-lab** [elytra/Albedo#14]
I encounter rendering inconsistencies, here's a video, and the snippet of my code used to do the animation.

Can you help me, is it a misconception on my side or a true rendering issue ?

[http://i.imgur.com/JOwBRRM.gifv](http://i.imgur.com/JOwBRRM.gifv)

```java
    private Float currentRadius = 1f;
    private Float currentIterator = 0f;
    private final Float getRadius(){
        if(this.currentIterator >= Math.PI*2) this.currentIterator = 0f;
        this.currentIterator += (float) Math.PI/1000;

        this.currentRadius = (float) Math.cos(Math.sin(this.currentIterator/5)*this.currentIterator)*5;
        return this.currentRadius;
    }

    @Optional.Method(modid="albedo")
    @Override
    public Light provideLight() {
        return Light.builder()
                .pos(
                        this.pos.getX() +0.5,
                        this.pos.getY() +0.5,
                        this.pos.getZ() +0.5
                )
                .color(0.2f,0.2f,0.2f)
                .radius(this.getRadius())
                .build();
    }
```

**Comment by exaskye** [comment]
I didn't get a notification about this issue for some reason.

This is... really weird.

**Comment by exaskye** [comment]
Does this issue still manifest on [a 2.0.2 build](https://ci.elytradev.com/job/elytra/job/Mirage/job/1.12/9/)? There have been a number of changes to the shader.

**Comment by kane-thornwyrd** [comment]
Testing now

**Comment by jena-th** [comment]
I fix my mod, I test, answer this WE

**Comment by jena-th** [comment]
FIXED ! (sorry, I hadn't much time, those months)
