### ISSUE TITLE
Broken Shaders

### ISSUE THREAD

**Issue by jredfox** [elytra/Albedo#5]
Version: 2.0 for mc 1.12
Images: http://imgur.com/a/pklr3

I am using my laptop with optifine so I can attempt shaders. It appears the mod doesn't work yet.

**Comment by asiekierka** [comment]
I wouldn't expect this mod to work with OptiFine ever, myself.

**Comment by jredfox** [comment]
It's worse without optifine:
http://imgur.com/a/62D4c

**Comment by asiekierka** [comment]
I know another person who has the same problem. What graphics card, operating system and driver version are you on?

**Comment by jredfox** [comment]
http://imgur.com/DVDKhNp

**Comment by asiekierka** [comment]
Intel drivers on Windows are historically not that great, but at least that's a lead...

**Comment by jredfox** [comment]
Well graphics works with optifine shaders no cubes better foliage
https://imgur.com/a/7qgCo

**Comment by ChloeDawn** [comment]
Hello! I am other person. Here are my GPU and OS specs:
```
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 970/PCIe/SSE2'
LWJGL: 2.9.1
OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.53, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
Using VBOs: Yes
CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
```
![GPU](http://i.imgur.com/ojAWH2X.png)
![OS](http://i.imgur.com/ef0CHaG.png)

**Comment by exaskye** [comment]
:ok_hand:

I'm pretty busy with other projects at the moment; I'll look into this Soon™

**Comment by sctjkc01** [comment]
@jredfox That's not quite enough information to go on - don't suppose you could provide information found in DxDiag?  Specifically around what graphics card you're using?

**Comment by exaskye** [comment]
@sctjkc01 - Gigabyte nVidia GTX 970, on driver version 21.21.13.7653; it's listed multiple times in his Speccy screenshots and the Minecraft crash report snippet.

**Comment by jredfox** [comment]
@sctjkc01 it's happening to people on desktops and laptops with or without intel as stated by @InsomniaKitten . This is the mods problem not my graphics card. For example I can run shaders with optifine . Your mod doesn't work with or without optifine.

**Comment by darkevilmac** [comment]
> This is the mods problem not my graphics card. For example I can run shaders with optifine . Your mod doesn't work with or without optifine.

Nobody said it wasn't a problem with the mod, if it wasn't a problem with the mod this issue would have been closed by now. It's just best to get as much information about the hardware and software that the bug is appearing on so progress can be made on fixing it.

**Comment by exaskye** [comment]
Yeah. Graphics programming is a special kind of hell; all graphics cards and driver versions are different. I use an open source driver on Linux, which is about as far removed from the common case as possible.

**Comment by asiekierka** [comment]
As a workaround, try disabling VBOs. Helps here.

**Comment by exaskye** [comment]
The [latest build](https://ci.elytradev.com/job/elytra/job/Albedo/job/1.11.2/10/) has the transformer updates from #2, and may fix some things similar to this issue.

I don't think it'll fix the solid-white blocks seen by the original reporter, but it has fixed a number of bugs I've been seeing.

**Comment by falkreon** [comment]
I finally did manage to reproduce this while tampering with other stuff - vanilla has chunkX / Y / Z uniforms and if those get clobbered, all the texture coords seem to hit that same solid color. I'm willing to bet that's an issue with the now-disabled entity and TESR shading. I'm closing this for now, but when I rewrite/reenable the entity code we'll need to do some testing to make sure it doesn't come back.
