### ISSUE TITLE
NO Colored Glowstone/Torches

### ISSUE THREAD

**Issue by jredfox** [elytra/Albedo#6]
Version: 2.0, mc 1.12

What's the point in colored lights if there are no colored lights? Seems terrible add some glowstone and torches that are colored via dyes so we can see some colored lights

**Comment by asiekierka** [comment]
First of all, these aren't colored lights in the traditional sense. They're intended for ambient effects more than actual in-world usage for building. This gives them the dynamicity, but this also means that having a lot of them in the same world will cause insane amounts of lag.

You might want a different colored light mod for this.

**Comment by jredfox** [comment]
Your stuff already supports colored lights add in some blocks that puts off some color please

**Comment by asiekierka** [comment]
You seem not to care about the technical reasons behind decisions, so I'll phrase it a bit more clearly:

There's a limit of 10 lights rendered at the same time by default. Yes, ten *lights*. Ten light sources. You can bring it up to 100 if you have a fast enough GPU. Are you sure you still want this? Are you sure you want the massive FPS drops?

Ambient, dynamic colored lights are designed for things which are ambient and/or dynamic. Static blocks in the world are neither, not to mention that Albedo's lights seem to be intended for a low radius as they go through walls pretty easily?

**Comment by jredfox** [comment]
Well then talk to **cptspacetoaster** since he got it working with multiple different blocks at the same time

**Comment by asiekierka** [comment]
@jredfox His system works completely differently from this one. It doesn't support dynamic lights or precise placement of lights, rather, it allows Minecraft's existing lights to have R, G and B components in addition to their light intensity.

**Comment by jredfox** [comment]
His supports dynamic lights mod though.

**Comment by asiekierka** [comment]
@jredfox Notice that AtomicStryker's Dynamic Lights take a very long time to update chunks, especially in 1.10+, whereas these lights update smoothly with every single frame.

**Comment by jredfox** [comment]
Well in my opinion the reason to make a colored lights mod is to have colored lights blocks but, either try or don't try **cptspacetoaster quit way before optifine made mostly compatible shaders backport with his mod**

**Comment by asiekierka** [comment]
@jredfox This is not strictly a colored lights mod. Not in the same sense you're thinking of.
