### ISSUE TITLE
Mark ILightProvider#provideLight nullable

### ISSUE THREAD

**Issue by raoulvdberge** [elytra/Albedo#8]
Since you check for null in LightManager#addLight anyway.

**Comment by exaskye** [comment]
There's no NonnullByDefault on the Albedo package, so is this flag actually useful?

**Comment by raoulvdberge** [comment]
It's mainly for code clarity for me, since I had to check in LightingManager to see if I could return null. Seeing `@Nullable` makes it clear instantly.
